/* File : main.c */
/* Deskripsi : Main Driver ADT list berkait circular dengan representasi fisik pointer */
/* NIM & Nama : 24060123120020 & Mohamad Solkhan Nawawi*/
/* Tanggal : Jum'at, 8 November 2024 */

#include <stdio.h>
#include "list2.h"
#include "list2.c"

int main () {
    //Kamus Lokal
    List2 Senarai_1, Senarai_2, Senarai_3, concatSenarai, splitSenarai_1, splitSenarai_2, copySenarai_1, copySenarai_2;
    List2 cobaSenarai_1, cobaSenarai_2, cobaSenarai_3;
    address P;

    //Algoritma
    printf("================== Aplikasi CreateList ==================\n");
    CreateList(&Senarai_1);
    printf("Senarai 1 berhasil dibuat\n");
    printf("\n");
    printf("================== Aplikasi IsEmptyList ==================\n");
    printf("Senarai 1 kosong? %s\n", IsEmptyList(Senarai_1) ? "True" : "False");
    printf("\n");
    printf("==================  Aplikasi IsOneElm   ==================\n");
    printf("Senarai 1 hanya punya satu elemen? %s\n", IsOneElm(Senarai_1) ? "True" : "False");
    printf("\n");
    printf("==================  Aplikasi NbElm ==================\n");
    printf("Banyaknya elemen pada Senarai 1 adalah %d\n", NbElm(Senarai_1));
    printf("\n");
    printf("==================  Aplikasi PrintList ==================\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi InsertVFirst ==================\n");
    printf("Menambahkan elemen 'A', 'B', 'C pada Senarai 1\n");
    InsertVFirst(&Senarai_1, 'A');
    InsertVFirst(&Senarai_1, 'B');
    InsertVFirst(&Senarai_1, 'C');
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi InsertVLast =================\n");
    printf("Menambahkan elemen 'D', 'E', 'F pada Senarai 2\n");
    InsertVLast(&Senarai_2, 'D');
    InsertVLast(&Senarai_2, 'E');
    InsertVLast(&Senarai_2, 'F');
    printf("Isi dari Senarai 2 adalah: ");
    PrintList(Senarai_2);
    printf("\n\n");
    printf("==================  Aplikasi DeleteVFirst =================\n");
    printf("Menghapus elemen pertama pada Senarai 1\n");
    printf("Isi dari Senarai 1 sebelum dihapus adalah: ");
    PrintList(Senarai_1);
    DeleteVFirst(&Senarai_1, &P);
    printf("\n");
    printf("Isi dari Senarai 1 setelah dihapus adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi DeleteVLast =================\n");
    printf("Menghapus elemen terakhir pada Senarai 2\n");
    printf("Isi dari Senarai 2 sebelum dihapus adalah: ");
    PrintList(Senarai_2);
    DeleteVLast(&Senarai_2, &P);
    printf("\n");
    printf("Isi dari Senarai 2 setelah dihapus adalah: ");
    PrintList(Senarai_2);
    printf("\n\n");
    printf("==================  Aplikasi DeleteX =================\n");
    printf("Menghapus elemen 'B' pada Senarai 1\n");
    printf("Isi dari Senarai 1 sebelum dihapus adalah: ");
    PrintList(Senarai_1);
    DeleteX(&Senarai_1, 'B');
    printf("\n");
    printf("Isi dari Senarai 1 setelah dihapus adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("Menghapus elemen 'Z' pada Senarai 2\n");
    printf("Isi dari Senarai 2 sebelum dihapus adalah: ");
    PrintList(Senarai_2);
    DeleteX(&Senarai_2, 'Z');
    printf("\n");
    printf("Isi dari Senarai 2 setelah dihapus adalah: ");
    PrintList(Senarai_2);
    printf("\n\n");
    printf("==================  Aplikasi SearchX =================\n");
    printf("Menambahkan elemen 'X', 'Y', 'Z' pada Senarai 1\n");
    InsertVLast(&Senarai_1, 'X');
    InsertVLast(&Senarai_1, 'Y');
    InsertVLast(&Senarai_1, 'Z');
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Mencari elemen 'Y' pada Senarai 1\n");
    SearchX(Senarai_1, 'Y', &P);
    printf("Elemen 'Y' ditemukan pada alamat %p\n", P);
    printf("\n");
    printf("Mencari elemen 'T' pada Senarai 1\n");
    SearchX(Senarai_1, 'T', &P);
    printf("Elemen 'T' ditemukan pada alamat %p\n", P);
    printf("\n");
    printf("==================  Aplikasi UpdateX =================\n");
    printf("Mengupdate elemen 'Z' menjadi 'W' pada Senarai 1\n");
    printf("Isi dari Senarai 1 sebelum diupdate adalah: ");
    PrintList(Senarai_1);
    UpdateX(&Senarai_1, 'Z', 'W');
    printf("\n");
    printf("Isi dari Senarai 1 setelah diupdate adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi Invers =================\n");
    printf("Membalikkan urutan elemen pada Senarai 1\n");
    printf("Isi dari Senarai 1 sebelum dibalikkan adalah: ");
    PrintList(Senarai_1);
    Invers(&Senarai_1);
    printf("\n");
    printf("Isi dari Senarai 1 setelah dibalikkan adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi CountX =================\n");
    CreateList(&Senarai_3);
    InsertVLast(&Senarai_3, 'K');
    InsertVLast(&Senarai_3, 'K');
    InsertVLast(&Senarai_3, 'L');
    InsertVLast(&Senarai_3, 'M');
    InsertVLast(&Senarai_3, 'K');
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Banyaknya elemen 'K' pada Senarai 3 adalah %d\n", CountX(Senarai_3, 'K'));
    printf("\n");
    printf("==================  Aplikasi FrekuensiX =================\n");
    printf("Frekuensi kemunculan elemen 'K' pada Senarai 3 adalah %.2f\n", FrekuensiX(Senarai_3, 'K'));
    printf("\n");
    printf("==================  Aplikasi CountVocal =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Banyaknya huruf vokal pada Senarai 3 adalah %d\n", CountVocal(Senarai_3));
    printf("\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Banyaknya huruf vokal pada Senarai 1 adalah %d\n", CountVocal(Senarai_1));
    printf("\n");
    printf("==================  Aplikasi CountNG =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Banyaknya huruf 'N' yang diikuti huruf 'G' pada Senarai 3 adalah %d\n", CountNG(Senarai_3));
    printf("\n");
    printf("Menambahkan elemen 'N', 'G', 'N', 'G', 'N', 'G' pada Senarai 3\n");
    InsertVLast(&Senarai_3, 'N');
    InsertVLast(&Senarai_3, 'G');
    InsertVLast(&Senarai_3, 'N');
    InsertVLast(&Senarai_3, 'G');
    InsertVLast(&Senarai_3, 'N');
    InsertVLast(&Senarai_3, 'G');
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Banyaknya huruf 'N' yang diikuti huruf 'G' pada Senarai 3 adalah %d\n", CountNG(Senarai_3));
    printf("\n");
    printf("==================  Aplikasi InsertVAfterX =================\n");
    InsertVFirst(&Senarai_1, 'W');
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Menambahkan elemen 'X' setelah elemen 'W' pada Senarai 1\n");
    InsertVAfterX(&Senarai_1, 'W', 'X');
    printf("Isi dari Senarai 1 setelah ditambahkan elemen 'X' adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi InsertVBeforeX =================\n");
    printf("Isi dari Senarai 2 adalah: ");
    PrintList(Senarai_2);
    printf("\n");
    printf("Menambahkan elemen 'Y' sebelum elemen 'E' pada Senarai 2\n");
    InsertVBeforeX(&Senarai_2, 'E', 'Y');
    printf("Isi dari Senarai 2 setelah ditambahkan elemen 'Y' adalah: ");
    PrintList(Senarai_2);
    printf("\n\n");
    printf("==================  Aplikasi DeleteVAfterX =================\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Menghapus elemen setelah elemen 'W' pada Senarai 1\n");
    DeleteVAfterX(&Senarai_1, 'W', &P);
    printf("Isi dari Senarai 1 setelah dihapus elemen setelah 'W' adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi DeleteVBeforeX =================\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Menghapus elemen sebelum elemen 'X' pada Senarai 1\n");
    DeleteVBeforeX(&Senarai_1, 'X', &P);
    printf("Isi dari Senarai 1 setelah dihapus elemen sebelum 'X' adalah: ");
    PrintList(Senarai_1);
    printf("\n\n");
    printf("==================  Aplikasi DeleteAllX =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Menghapus semua elemen 'N' pada Senarai 3\n");
    DeleteAllX(&Senarai_3, 'N');
    printf("Isi dari Senarai 3 setelah dihapus semua elemen 'N' adalah: ");
    PrintList(Senarai_3);
    printf("\n\n");
    printf("==================  Aplikasi SearchAllX =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Mencari semua elemen 'G' pada Senarai 3\n");
    printf("Elemen 'G' ditemukan pada posisi: ");
    SearchAllX(Senarai_3, 'G');
    printf("\n");
    printf("Mencari semua elemen 'Z' pada Senarai 3\n");
    printf("Elemen 'Z' ditemukan pada posisi: ");
    SearchAllX(Senarai_3, 'Z');
    printf("\n\n");
    printf("==================  Aplikasi MaxMember =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Banyaknya elemen yang paling banyak muncul pada Senarai 3 adalah %d\n", MaxMember(Senarai_3));
    printf("\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Banyaknya elemen yang paling banyak muncul pada Senarai 1 adalah %d\n", MaxMember(Senarai_1));
    printf("\n\n");
    printf("==================  Aplikasi Modus =================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Huruf yang paling banyak muncul pada Senarai 3 adalah %c\n", Modus(Senarai_3));
    printf("\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Huruf yang paling banyak muncul pada Senarai 1 adalah %c\n", Modus(Senarai_1));
    printf("\n");
    printf("==================  ConcatList =================\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Isi dari Senarai 2 adalah: ");
    PrintList(Senarai_2);
    printf("\n");
    printf("Menggabungkan Senarai 1 dan Senarai 2\n");
    ConcatList(Senarai_1, Senarai_2, &concatSenarai);
    printf("Isi dari Senarai 1 setelah digabungkan dengan Senarai 2 adalah: ");
    PrintList(concatSenarai);
    printf("\n\n");
    printf("================== SplitList===================\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Membagi Senarai 3 menjadi dua\n");
    SplitList(Senarai_3, &splitSenarai_1, &splitSenarai_2);
    printf("Isi dari Senarai 3 setelah dibagi adalah: ");
    printf("\n");
    printf("Isi dari splitSenarai_1 adalah: ");
    PrintList(splitSenarai_1);
    printf("\n");
    printf("Isi dari splitSenarai_2 adalah: ");
    PrintList(splitSenarai_2);
    printf("\n\n");
    printf("================== CopyList===================\n");
    printf("Isi dari Senarai 1 adalah: ");
    PrintList(Senarai_1);
    printf("\n");
    printf("Mengcopy Senarai 1 ke copySenarai_1\n");
    CopyList(Senarai_1, &copySenarai_1);
    printf("Isi dari copySenarai_1 adalah: ");
    PrintList(copySenarai_1);
    printf("\n\n");
    printf("Isi dari Senarai 3 adalah: ");
    PrintList(Senarai_3);
    printf("\n");
    printf("Mengcopy Senarai 3 ke copySenarai_2\n");
    CopyList(Senarai_3, &copySenarai_2);
    printf("Isi dari copySenarai_2 adalah: ");
    PrintList(copySenarai_2);
    printf("\n\n");

    printf("============== Menguji fungsi-fungsi predikat ===============\n");
    CreateList(&cobaSenarai_1);
    CreateList(&cobaSenarai_2);
    CreateList(&cobaSenarai_3);
    printf("Menambahkan elemen 'A', 'B', 'C', 'D', 'E', 'F' pada cobaSenarai_1\n");
    InsertVLast(&cobaSenarai_1, 'A');
    InsertVLast(&cobaSenarai_1, 'B');
    InsertVLast(&cobaSenarai_1, 'C');
    InsertVLast(&cobaSenarai_1, 'D');
    InsertVLast(&cobaSenarai_1, 'E');
    InsertVLast(&cobaSenarai_1, 'F');
    printf("Isi dari cobaSenarai_1 adalah: ");
    PrintList(cobaSenarai_1);
    printf("\n");
    printf("Menambahkan elemen 'Z' pada cobaSenarai_2\n");
    InsertVLast(&cobaSenarai_2, 'Z');
    printf("Isi dari cobaSenarai_2 adalah: ");
    PrintList(cobaSenarai_2);
    printf("\n");
    printf("Tidak Menambahkan elemen apapun pada cobaSenarai_3\n");
    printf("Isi dari cobaSenarai_3 adalah: ");
    PrintList(cobaSenarai_3);
    printf("\n\n");
    printf("cobaSenarai_1 kosong? %s\n", IsEmptyList(cobaSenarai_1) ? "True" : "False");
    printf("cobaSenarai_2 kosong? %s\n", IsEmptyList(cobaSenarai_2) ? "True" : "False");
    printf("cobaSenarai_3 kosong? %s\n", IsEmptyList(cobaSenarai_3) ? "True" : "False");
    printf("cobaSenarai_1 hanya punya satu elemen? %s\n", IsOneElm(cobaSenarai_1) ? "True" : "False");
    printf("cobaSenarai_2 hanya punya satu elemen? %s\n", IsOneElm(cobaSenarai_2) ? "True" : "False");
    printf("cobaSenarai_3 hanya punya satu elemen? %s\n", IsOneElm(cobaSenarai_3) ? "True" : "False");
    printf("\n");
    printf("Banyaknya elemen pada cobaSenarai_1 adalah %d\n", NbElm(cobaSenarai_1));
    printf("Banyaknya elemen pada cobaSenarai_2 adalah %d\n", NbElm(cobaSenarai_2));
    printf("Banyaknya elemen pada cobaSenarai_3 adalah %d\n", NbElm(cobaSenarai_3));
    printf("\n");
    return 0;
}