/* File : main.c */
/* Deskripsi : Main Driver ADT bintree3 berkait dengan representasi fisik pointer */
/* NIM & Nama : 24060123120020 & Mohamad Solkhan Nawawi*/
/* Tanggal : Jum'at, 06 Desember 2024*/

#include <stdio.h>
#include <stdlib.h>
#include "pohon3.h"
#include "pohon3.c"
int main() {
	//Kamus
	bintree3 W, B, C, D, E, F;
    bintree3 pohonUnerLeft, pohonUnerRight;
    bintree3 pohonDaun, pohonBiner, pohonKosong;
    List1 Asli, Tambahan, Bumbu;
    List1 Asli_2, Tambahan_2;

	//Algoritma
    printf("======= Test Tree3 =======\n");
    D = Tree3(NULL, 'D', False, NULL, NULL);
    E = Tree3(NULL, 'E', False, NULL, NULL);
    F = Tree3(NULL, 'F', False, NULL, NULL);
    B = Tree3(NULL, 'B', False, NULL, D);
    C = Tree3(NULL, 'C', False, E, F);
    W = Tree3(NULL, 'A', False, B, C);
    D->parent = B;
    E->parent = C;
    F->parent = C;
    B->parent = W;
    C->parent = W;

    pohonUnerLeft = Tree3(NULL, 'A', False, B, NULL);
    pohonUnerRight = Tree3(NULL, 'A', False, NULL, C);
    pohonDaun = Tree3(NULL, 'A', False, NULL, NULL);
    pohonBiner = Tree3(NULL, 'A', False, B, C);
    pohonKosong = NIL;

    printf("======= Test printDFS =======\n");
    printf("Pohon W : \n");
	printDFS(W);
    printf("\n\n");
    printf("Pohon Daun : \n");
    printDFS(pohonDaun);
    printf("\n\n");
    printf("Pohon Biner : \n");
    printDFS(pohonBiner);
    printf("\n\n");
    printf("Pohon Uner Left : \n");
    printDFS(pohonUnerLeft);
    printf("\n\n");
    printf("Pohon Uner Right : \n");
    printDFS(pohonUnerRight);
    printf("\n\n");
    printf("======= Test printParent =======\n");
    printParent(W);
    printf("\n\n");
    printf("======= Test risetVisited =======\n"); 
    printf("Pohon W : \n");
    printDFS(W);
    resetVisited(W);
    printf("\n\n");
    printf("======= Test IsEmptyTree =======\n");
    printf("Pohon W : ");
    printf("%s\n",IsEmptyTree(W)?"Kosong":"Tidak Kosong");
    printf("\n\n");
    printf("Pohon Kosong : ");
    printf("%s\n",IsEmptyTree(pohonKosong)?"Kosong":"Tidak Kosong");
    printf("\n\n");
    printf("======= Test IsDaun =======\n");
    printf("Pohon W : ");
    printf("%s\n",IsDaun(W)?"Daun":"Bukan Daun");
    printf("\n\n");
    printf("Pohon Daun : ");
    printf("%s\n",IsDaun(pohonDaun)?"Daun":"Bukan Daun");
    printf("\n\n");
    printf("======= Test IsBiner =======\n");
    printf("Pohon W : ");
    printf("%s\n",IsBiner(W)?"Biner":"Bukan Biner");
    printf("\n\n");
    printf("Pohon Biner : ");
    printf("%s\n",IsBiner(pohonBiner)?"Biner":"Bukan Biner");
    printf("\n\n");
    printf("======= Test IsUnerLeft =======\n");
    printf("Pohon W : ");
    printf("%s\n",IsUnerLeft(W)?"Uner Left":"Bukan Uner Left");
    printf("\n\n");
    printf("Pohon Uner Left : ");
    printf("%s\n",IsUnerLeft(pohonUnerLeft)?"Uner Left":"Bukan Uner Left");
    printf("\n\n");
    printf("======= Test IsUnerRight =======\n");
    printf("Pohon W : ");
    printf("%s\n",IsUnerRight(W)?"Uner Right":"Bukan Uner Right");
    printf("\n\n");
    printf("Pohon Uner Right : ");
    printf("%s\n",IsUnerRight(pohonUnerRight)?"Uner Right":"Bukan Uner Right");
    printf("\n\n");
    printf("======= Test printPathX =======\n");
    printf("Jalur dari akar W hingga node bernilai D : ");
    printPathX(W,'D');
    printf("\n\n");
    printf("Jalur dari akar W hingga node bernilai E : ");
    printPathX(W,'E');
    printf("\n\n");
    printf("======= Test printPathDaunX =======\n");
    printf("Jalur dari akar W hingga daun bernilai D : ");
    printPathDaunX(W,'D');
    printf("\n\n");
    printf("Jalur dari akar W hingga daun bernilai E : ");
    printPathDaunX(W,'E');
    printf("\n\n");
    printf("Jalur dari akar W hingga daun bernilai B : ");
    printPathDaunX(W,'B');
    printf("\n\n");
    printf("======= Test printAllPaths =======\n");
    printf("Semua jalur dari akar W hingga daun : \n");
    printAllPaths(W);
    printf("\n\n");
    printf("======= Test NbElmtTree =======\n");
    printf("Jumlah node pada pohon W : %d\n\n",NbElmTree(W));
    printf("======= Test NbDaun =======\n");
    printf("Jumlah daun pada pohon W : %d\n\n",NbDaun(W));
    printf("======= Test Tinggi =======\n");
    printf("Tinggi pohon W : %d\n\n",Tinggi(W));
    printf("======= Test Level =======\n");
    printf("Level dari pohon W : %d\n\n",Level(W));
    printf("======= Test CountLevelT =======\n");
    printf("Jumlah node pada level 1 pohon W : %d\n",CountLevelT(W,1));
    printf("Jumlah node pada level 2 pohon W : %d\n",CountLevelT(W,2));
    printf("Jumlah node pada level 3 pohon W : %d\n\n",CountLevelT(W,3));
    printf("======= Test PrintLevel =======\n");
    printf("Elemen pada level 1 pohon W : ");
    PrintLevel(W,1);
    printf("\n\n");
    printf("Elemen pada level 2 pohon W : ");
    PrintLevel(W,2);
    printf("\n\n");
    printf("Elemen pada level 3 pohon W : ");
    PrintLevel(W,3);
    printf("\n\n");
    printf("======= Test PrintBFS =======\n");
    printf("Pohon W : \n");
    PrintBFS(W);
    printf("\n\n");
    printf("======= Test Pconcat =======\n");
    CreateList(&Asli);
    CreateList(&Tambahan);
    InsertVLast(&Asli, 'A');
    InsertVLast(&Asli, 'K');
    InsertVLast(&Asli, 'U');
    InsertVLast(&Tambahan, 'S');
    InsertVLast(&Tambahan, 'U');
    InsertVLast(&Tambahan, 'K');
    InsertVLast(&Tambahan, 'A');
    printf("List1 Asli : ");
    PrintList(Asli);
    printf("\n\n");
    printf("List1 Tambahan : ");
    PrintList(Tambahan);
    printf("\n\n");
    Pconcat(&Asli, Tambahan);
    printf("Hasil Pconcat : ");
    PrintList(Asli);
    printf("\n\n");
    CreateList(&Bumbu);
    InsertVLast(&Bumbu, 'K');
    InsertVLast(&Bumbu, 'A');
    InsertVLast(&Bumbu, 'M');
    InsertVLast(&Bumbu, 'U');
    printf("List1 Bumbu : ");
    PrintList(Bumbu);
    printf("\n\n");
    Pconcat(&Asli, Bumbu);
    printf("Hasil Pconcat : ");
    PrintList(Asli);
    printf("\n\n");
    printf("======= Test Fconcat =======\n");
    CreateList(&Asli_2);
    CreateList(&Tambahan_2);
    InsertVLast(&Asli_2, 'U');
    InsertVLast(&Asli_2, 'N');
    InsertVLast(&Asli_2, 'D');
    InsertVLast(&Tambahan_2, 'I');
    InsertVLast(&Tambahan_2, 'P');
    printf("List1 Asli_2 : ");
    PrintList(Asli_2);
    printf("\n\n");
    printf("List1 Tambahan_2 : ");
    PrintList(Tambahan_2);
    printf("\n\n");
    Fconcat(Asli_2, Tambahan_2);
    printf("Hasil Fconcat : ");
    PrintList(Fconcat(Asli_2, Tambahan_2));
    printf("\n\n");
    printf("List1 Asli_2 : ");
    PrintList(Asli_2);
    printf("\n\n");
    printf("======= Test LinearPrefix =======\n");
    printf("Pohon W : ");
    printDFS(W);
    printf("\n\n");
    printf("Hasil LinearPrefix : ");
    PrintList(LinearPrefix(W));
    printf("\n\n");
    printf("======= Test LinearPosfix =======\n");
    printf("Pohon W : ");
    printDFS(W);
    printf("\n\n");
    printf("Hasil LinearPosfix : ");
    PrintList(LinearPosfix(W));
    printf("\n\n");
    printf("======= Test LinearInfix =======\n");
    printf("Pohon W : ");
    printDFS(W);
    printf("\n\n");
    printf("Hasil LinearInfix : ");
    PrintList(LinearInfix(W));
    printf("\n\n");
    printf("======= Test LinearBreadthFS =======\n");
    printf("Pohon W : ");
    printDFS(W);
    printf("\n\n");
    printf("Hasil LinearBreadthFS : ");
    PrintList(LinearBreadthFS(W));
    printf("\n\n");
    return 0;
}