CREATE TABLE  `REGIONS`
   (`REGION_ID` DOUBLE  NOT NULL,
    `REGION_NAME` VARCHAR(25),
    CONSTRAINT `REG_ID_PK` PRIMARY KEY (`REGION_ID`)
   );
   
CREATE TABLE  `COUNTRIES`
   (`COUNTRY_ID` CHAR(2)  NOT NULL,
    `COUNTRY_NAME` VARCHAR(40),
    `REGION_ID` DOUBLE,
     CONSTRAINT `COUNTRY_C_ID_PK` PRIMARY KEY (`COUNTRY_ID`) 
   );

ALTER TABLE  `COUNTRIES` ADD CONSTRAINT `COUNTR_REG_FK` FOREIGN KEY (`REGION_ID`)
	REFERENCES  `REGIONS` (`REGION_ID`);
   
CREATE TABLE  `LOCATIONS`
   (`LOCATION_ID` SMALLINT,
    `STREET_ADDRESS` VARCHAR(40),
    `POSTAL_CODE` VARCHAR(12),
    `CITY` VARCHAR(30)  NOT NULL,
    `STATE_PROVINCE` VARCHAR(25),
    `COUNTRY_ID` CHAR(2),
    CONSTRAINT `LOC_ID_PK` PRIMARY KEY (`LOCATION_ID`)
   );
   
ALTER TABLE  `LOCATIONS` ADD CONSTRAINT `LOC_C_ID_FK` FOREIGN KEY (`COUNTRY_ID`)
	REFERENCES  `COUNTRIES` (`COUNTRY_ID`);
CREATE INDEX  `LOC_CITY_IX` ON  `LOCATIONS` (`CITY`);
CREATE INDEX  `LOC_COUNTRY_IX` ON  `LOCATIONS` (`COUNTRY_ID`);
CREATE INDEX  `LOC_STATE_PROVINCE_IX` ON  `LOCATIONS` (`STATE_PROVINCE`);

CREATE TABLE  `DEPARTMENTS`
   (`DEPARTMENT_ID` SMALLINT,
    `DEPARTMENT_NAME` VARCHAR(30)  NOT NULL,
    `MANAGER_ID` INT,
    `LOCATION_ID` SMALLINT,
     CONSTRAINT `DEPT_ID_PK` PRIMARY KEY (`DEPARTMENT_ID`)
   );
 
ALTER TABLE  `DEPARTMENTS` ADD CONSTRAINT `DEPT_LOC_FK` FOREIGN KEY (`LOCATION_ID`)
	REFERENCES  `LOCATIONS` (`LOCATION_ID`);

CREATE INDEX  `DEPT_LOCATION_IX` ON  `DEPARTMENTS` (`LOCATION_ID`);
	
CREATE TABLE  `JOBS`
   (`JOB_ID` VARCHAR(10),
    `JOB_TITLE` VARCHAR(35)  NOT NULL,
    `MIN_SALARY` INT,
    `MAX_SALARY` INT,
     CONSTRAINT `JOB_ID_PK` PRIMARY KEY (`JOB_ID`)
   );
	
CREATE TABLE  `EMPLOYEES`
   (`EMPLOYEE_ID` INT,
    `FIRST_NAME` VARCHAR(20),
    `LAST_NAME` VARCHAR(25)  NOT NULL,
    `EMAIL` VARCHAR(25)  NOT NULL,
    `PHONE_NUMBER` VARCHAR(20),
    `HIRE_DATE` DATETIME  NOT NULL,
    `JOB_ID` VARCHAR(10)  NOT NULL,
    `SALARY` DECIMAL(8,2),
    `COMMISSION_PCT` DECIMAL(2,2),
    `MANAGER_ID` INT,
    `DEPARTMENT_ID` SMALLINT,
	`BONUS` VARCHAR(5),
     CONSTRAINT `EMP_SALARY_MIN` CHECK (salary > 0),
     CONSTRAINT `EMP_ID_PK` PRIMARY KEY (`EMPLOYEE_ID`)
  ,
     CONSTRAINT `EMP_EMAIL_UK` UNIQUE (`EMAIL`)
  );
  
ALTER TABLE  `EMPLOYEES` ADD CONSTRAINT `EMP_DEPT_FK` FOREIGN KEY (`DEPARTMENT_ID`)
	REFERENCES  `DEPARTMENTS` (`DEPARTMENT_ID`);
ALTER TABLE  `EMPLOYEES` ADD CONSTRAINT `EMP_JOB_FK` FOREIGN KEY (`JOB_ID`)
	REFERENCES  `JOBS` (`JOB_ID`);
ALTER TABLE  `EMPLOYEES` ADD CONSTRAINT `EMP_MANAGER_FK` FOREIGN KEY (`MANAGER_ID`)
	REFERENCES  `EMPLOYEES` (`EMPLOYEE_ID`);
ALTER TABLE  `DEPARTMENTS` ADD CONSTRAINT `DEPT_MGR_FK` FOREIGN KEY (`MANAGER_ID`)
	REFERENCES  `EMPLOYEES` (`EMPLOYEE_ID`);
CREATE INDEX  `EMP_DEPARTMENT_IX` ON  `EMPLOYEES` (`DEPARTMENT_ID`);
CREATE INDEX  `EMP_JOB_IX` ON  `EMPLOYEES` (`JOB_ID`);
CREATE INDEX  `EMP_MANAGER_IX` ON  `EMPLOYEES` (`MANAGER_ID`);
CREATE INDEX  `EMP_NAME_IX` ON  `EMPLOYEES` (`LAST_NAME`, `FIRST_NAME`);

CREATE TABLE  `JOB_HISTORY`
   (`EMPLOYEE_ID` INT  NOT NULL,
    `START_DATE` DATETIME  NOT NULL,
    `END_DATE` DATETIME  NOT NULL,
    `JOB_ID` VARCHAR(10)  NOT NULL,
    `DEPARTMENT_ID` SMALLINT,
     CONSTRAINT `JHIST_DATE_INTERVAL` CHECK (end_date > start_date),
     CONSTRAINT `JHIST_EMP_ID_ST_DATE_PK` PRIMARY KEY (`EMPLOYEE_ID`, `START_DATE`)
   );

ALTER TABLE  `JOB_HISTORY` ADD CONSTRAINT `JHIST_DEPT_FK` FOREIGN KEY (`DEPARTMENT_ID`)
	REFERENCES  `DEPARTMENTS` (`DEPARTMENT_ID`);
-- SQLINES DEMO *** onstraint is disabled as table contains historical data for employees that are not in the current employees table
ALTER TABLE  `JOB_HISTORY` ADD CONSTRAINT `JHIST_EMP_FK` FOREIGN KEY (`EMPLOYEE_ID`)
	  REFERENCES  `EMPLOYEES` (`EMPLOYEE_ID`);
ALTER TABLE  `JOB_HISTORY` ADD CONSTRAINT `JHIST_JOB_FK` FOREIGN KEY (`JOB_ID`)
	  REFERENCES  `JOBS` (`JOB_ID`);
CREATE INDEX  `JHIST_DEPARTMENT_IX` ON  `JOB_HISTORY` (`DEPARTMENT_ID`);
CREATE INDEX  `JHIST_EMPLOYEE_IX` ON  `JOB_HISTORY` (`EMPLOYEE_ID`);
CREATE INDEX  `JHIST_JOB_IX` ON  `JOB_HISTORY` (`JOB_ID`);
